export interface Product {
  id: string;
  name: string;
  category: 'laptop' | 'desktop' | 'tablet' | 'accessories';
  brand: string;
  price: number;
  rating: number;
  reviews: number;
  image: string;
  images: string[];
  description: string;
  specs: Record<string, string>;
  inStock: boolean;
  discount?: number;
  featured?: boolean;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'MacBook Air M2',
    category: 'laptop',
    brand: 'Apple',
    price: 79999,
    rating: 4.8,
    reviews: 245,
    image: '/products/macbook-air-m2.jpg',
    images: ['/products/macbook-air-m2.jpg', '/products/macbook-air-m2-2.jpg'],
    description: 'Ultra-thin and powerful MacBook Air with M2 chip. Perfect for professionals and students.',
    specs: {
      'Processor': 'Apple M2',
      'RAM': '8GB',
      'Storage': '256GB SSD',
      'Display': '13.6" Liquid Retina',
      'Weight': '1.24 kg',
      'Battery': 'Up to 15 hours',
    },
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'MacBook Pro 14"',
    category: 'laptop',
    brand: 'Apple',
    price: 189999,
    rating: 4.9,
    reviews: 312,
    image: '/products/macbook-pro-14.jpg',
    images: ['/products/macbook-pro-14.jpg', '/products/macbook-pro-14-2.jpg'],
    description: 'Professional-grade laptop with M3 Pro chip, ideal for creative professionals.',
    specs: {
      'Processor': 'Apple M3 Pro',
      'RAM': '18GB',
      'Storage': '512GB SSD',
      'Display': '14" Liquid Retina XDR',
      'Weight': '1.60 kg',
      'Battery': 'Up to 17 hours',
    },
    inStock: true,
    featured: true,
    discount: 5,
  },
  {
    id: '3',
    name: 'HP Pavilion 15',
    category: 'laptop',
    brand: 'HP',
    price: 54999,
    rating: 4.5,
    reviews: 187,
    image: '/products/hp-pavilion-15.jpg',
    images: ['/products/hp-pavilion-15.jpg', '/products/hp-pavilion-15-2.jpg'],
    description: 'Affordable yet powerful HP laptop perfect for everyday computing and work.',
    specs: {
      'Processor': 'Intel i5-12th Gen',
      'RAM': '8GB DDR4',
      'Storage': '512GB SSD',
      'Display': '15.6" Full HD',
      'Weight': '1.74 kg',
      'Battery': 'Up to 8 hours',
    },
    inStock: true,
  },
  {
    id: '4',
    name: 'Dell XPS 13',
    category: 'laptop',
    brand: 'Dell',
    price: 89999,
    rating: 4.7,
    reviews: 298,
    image: '/products/dell-xps-13.jpg',
    images: ['/products/dell-xps-13.jpg', '/products/dell-xps-13-2.jpg'],
    description: 'Premium ultrabook with stunning InfinityEdge display and powerful performance.',
    specs: {
      'Processor': 'Intel i7-1360P',
      'RAM': '16GB LPDDR5',
      'Storage': '512GB SSD',
      'Display': '13.4" FHD+ InfinityEdge',
      'Weight': '1.2 kg',
      'Battery': 'Up to 12 hours',
    },
    inStock: true,
    featured: true,
  },
  {
    id: '5',
    name: 'Lenovo ThinkPad E15',
    category: 'laptop',
    brand: 'Lenovo',
    price: 59999,
    rating: 4.6,
    reviews: 156,
    image: '/products/lenovo-thinkpad-e15.jpg',
    images: ['/products/lenovo-thinkpad-e15.jpg', '/products/lenovo-thinkpad-e15-2.jpg'],
    description: 'Business-focused laptop with excellent keyboard and productivity features.',
    specs: {
      'Processor': 'Intel i7-12th Gen',
      'RAM': '16GB DDR4',
      'Storage': '512GB SSD',
      'Display': '15.6" FHD IPS',
      'Weight': '1.85 kg',
      'Battery': 'Up to 10 hours',
    },
    inStock: true,
  },
  {
    id: '6',
    name: 'ASUS VivoBook 14',
    category: 'laptop',
    brand: 'ASUS',
    price: 44999,
    rating: 4.4,
    reviews: 203,
    image: '/products/asus-vivobook-14.jpg',
    images: ['/products/asus-vivobook-14.jpg', '/products/asus-vivobook-14-2.jpg'],
    description: 'Stylish and portable laptop for students and young professionals.',
    specs: {
      'Processor': 'AMD Ryzen 5 5500U',
      'RAM': '8GB DDR4',
      'Storage': '256GB SSD',
      'Display': '14" FHD IPS',
      'Weight': '1.4 kg',
      'Battery': 'Up to 10 hours',
    },
    inStock: true,
  },
  {
    id: '7',
    name: 'MSI GE76 Raider',
    category: 'laptop',
    brand: 'MSI',
    price: 139999,
    rating: 4.7,
    reviews: 289,
    image: '/products/msi-ge76-raider.jpg',
    images: ['/products/msi-ge76-raider.jpg', '/products/msi-ge76-raider-2.jpg'],
    description: 'High-performance gaming laptop with RTX 3060 and 165Hz display.',
    specs: {
      'Processor': 'Intel i7-12th Gen',
      'RAM': '16GB DDR4',
      'Storage': '512GB SSD',
      'Display': '17.3" 165Hz FHD',
      'GPU': 'NVIDIA RTX 3060',
      'Weight': '2.6 kg',
    },
    inStock: true,
  },
  {
    id: '8',
    name: 'Samsung Galaxy Tab S9',
    category: 'tablet',
    brand: 'Samsung',
    price: 49999,
    rating: 4.6,
    reviews: 134,
    image: '/products/samsung-tab-s9.jpg',
    images: ['/products/samsung-tab-s9.jpg', '/products/samsung-tab-s9-2.jpg'],
    description: 'Premium tablet with brilliant AMOLED display and S Pen included.',
    specs: {
      'Processor': 'Snapdragon 8 Gen 1',
      'RAM': '8GB',
      'Storage': '128GB',
      'Display': '11" AMOLED 120Hz',
      'Battery': '8000 mAh',
      'Weight': '498g',
    },
    inStock: true,
  },
  {
    id: '9',
    name: 'iPad Air',
    category: 'tablet',
    brand: 'Apple',
    price: 59999,
    rating: 4.8,
    reviews: 267,
    image: '/products/ipad-air.jpg',
    images: ['/products/ipad-air.jpg', '/products/ipad-air-2.jpg'],
    description: 'Versatile tablet with M1 chip and Apple Pencil support.',
    specs: {
      'Processor': 'Apple M1',
      'RAM': '8GB',
      'Storage': '256GB',
      'Display': '10.9" Liquid Retina',
      'Battery': '8600 mAh',
      'Weight': '462g',
    },
    inStock: true,
    featured: true,
  },
  {
    id: '10',
    name: 'Dell OptiPlex Desktop',
    category: 'desktop',
    brand: 'Dell',
    price: 79999,
    rating: 4.5,
    reviews: 145,
    image: '/products/dell-optiplex.jpg',
    images: ['/products/dell-optiplex.jpg', '/products/dell-optiplex-2.jpg'],
    description: 'Reliable business desktop PC ideal for office environments.',
    specs: {
      'Processor': 'Intel i7-12th Gen',
      'RAM': '16GB DDR4',
      'Storage': '512GB SSD',
      'GPU': 'Intel Integrated',
      'PSU': '400W',
      'Case': 'Mid Tower',
    },
    inStock: true,
  },
  {
    id: '11',
    name: 'HP ProDesk 400',
    category: 'desktop',
    brand: 'HP',
    price: 69999,
    rating: 4.4,
    reviews: 98,
    image: '/products/hp-prodesk-400.jpg',
    images: ['/products/hp-prodesk-400.jpg', '/products/hp-prodesk-400-2.jpg'],
    description: 'Compact and efficient desktop for professional work.',
    specs: {
      'Processor': 'Intel i5-12th Gen',
      'RAM': '8GB DDR4',
      'Storage': '256GB SSD',
      'GPU': 'Intel Integrated',
      'PSU': '280W',
      'Case': 'Small Form Factor',
    },
    inStock: true,
  },
  {
    id: '12',
    name: 'Lenovo ThinkCentre',
    category: 'desktop',
    brand: 'Lenovo',
    price: 74999,
    rating: 4.5,
    reviews: 112,
    image: '/products/lenovo-thinkcentre.jpg',
    images: ['/products/lenovo-thinkcentre.jpg', '/products/lenovo-thinkcentre-2.jpg'],
    description: 'Robust desktop with excellent security features and performance.',
    specs: {
      'Processor': 'Intel i7-12th Gen',
      'RAM': '16GB DDR4',
      'Storage': '512GB SSD',
      'GPU': 'Intel Integrated',
      'PSU': '500W',
      'Case': 'Mid Tower',
    },
    inStock: true,
  },
  {
    id: '13',
    name: 'Wireless Mouse',
    category: 'accessories',
    brand: 'Logitech',
    price: 2499,
    rating: 4.6,
    reviews: 567,
    image: '/products/wireless-mouse.jpg',
    images: ['/products/wireless-mouse.jpg', '/products/wireless-mouse-2.jpg'],
    description: 'Comfortable wireless mouse with precision tracking.',
    specs: {
      'Type': 'Wireless 2.4GHz',
      'DPI': 'Adjustable 400-4000',
      'Battery': 'AA x2',
      'Life': 'Up to 24 months',
      'Buttons': '3',
      'Weight': '85g',
    },
    inStock: true,
  },
  {
    id: '14',
    name: 'Mechanical Keyboard',
    category: 'accessories',
    brand: 'Corsair',
    price: 8999,
    rating: 4.7,
    reviews: 423,
    image: '/products/mechanical-keyboard.jpg',
    images: ['/products/mechanical-keyboard.jpg', '/products/mechanical-keyboard-2.jpg'],
    description: 'Premium RGB mechanical keyboard with cherry switches.',
    specs: {
      'Switch': 'Cherry MX Red',
      'Backlit': 'RGB',
      'Layout': 'Full Size',
      'Cable': '1.8m USB',
      'Weight': '950g',
      'Material': 'Aluminum',
    },
    inStock: true,
  },
  {
    id: '15',
    name: 'USB-C Hub',
    category: 'accessories',
    brand: 'Anker',
    price: 3999,
    rating: 4.5,
    reviews: 289,
    image: '/products/usb-c-hub.jpg',
    images: ['/products/usb-c-hub.jpg', '/products/usb-c-hub-2.jpg'],
    description: '7-in-1 USB-C hub with multiple ports for connectivity.',
    specs: {
      'Ports': 'HDMI, USB 3.0 x2, SD Card',
      'Type': 'USB-C 3.1',
      'Power': '100W Pass-through',
      'Material': 'Aluminum',
      'Length': '0.2m',
      'Weight': '60g',
    },
    inStock: true,
  },
  {
    id: '16',
    name: 'Laptop Stand',
    category: 'accessories',
    brand: 'Rain Design',
    price: 4499,
    rating: 4.8,
    reviews: 178,
    image: '/products/laptop-stand.jpg',
    images: ['/products/laptop-stand.jpg', '/products/laptop-stand-2.jpg'],
    description: 'Ergonomic aluminum laptop stand for better posture.',
    specs: {
      'Material': 'Aluminum Alloy',
      'Compatibility': 'Up to 17"',
      'Adjustable': 'Yes',
      'Weight Capacity': '10 kg',
      'Color': 'Silver',
      'Weight': '350g',
    },
    inStock: true,
  },
  {
    id: '17',
    name: 'Portable SSD 1TB',
    category: 'accessories',
    brand: 'Samsung',
    price: 12999,
    rating: 4.7,
    reviews: 312,
    image: '/products/portable-ssd.jpg',
    images: ['/products/portable-ssd.jpg', '/products/portable-ssd-2.jpg'],
    description: 'Fast portable SSD with 1050MB/s transfer speed.',
    specs: {
      'Capacity': '1TB',
      'Interface': 'USB 3.2 Gen 2',
      'Speed': '1050MB/s',
      'Security': 'Hardware Encryption',
      'Durability': 'IP65 Rated',
      'Weight': '90g',
    },
    inStock: true,
  },
  {
    id: '18',
    name: 'Wireless Charger',
    category: 'accessories',
    brand: 'Belkin',
    price: 2999,
    rating: 4.4,
    reviews: 201,
    image: '/products/wireless-charger.jpg',
    images: ['/products/wireless-charger.jpg', '/products/wireless-charger-2.jpg'],
    description: 'Fast wireless charging pad for compatible devices.',
    specs: {
      'Power': '15W Fast Charge',
      'Compatibility': 'Qi Certified',
      'Input': 'USB-C',
      'Color': 'White/Black',
      'Dimensions': '100mm',
      'Weight': '65g',
    },
    inStock: true,
  },
  {
    id: '19',
    name: 'Webcam Pro',
    category: 'accessories',
    brand: 'Logitech',
    price: 5999,
    rating: 4.6,
    reviews: 267,
    image: '/products/webcam-pro.jpg',
    images: ['/products/webcam-pro.jpg', '/products/webcam-pro-2.jpg'],
    description: '4K UHD webcam for professional video calls and streaming.',
    specs: {
      'Resolution': '4K UHD 30fps',
      'Field of View': '90°',
      'Autofocus': 'Yes',
      'Microphone': 'Dual Built-in',
      'Cable': '1.5m USB',
      'Weight': '192g',
    },
    inStock: true,
  },
  {
    id: '20',
    name: 'Headphones Pro',
    category: 'accessories',
    brand: 'Sony',
    price: 24999,
    rating: 4.8,
    reviews: 445,
    image: '/products/headphones-pro.jpg',
    images: ['/products/headphones-pro.jpg', '/products/headphones-pro-2.jpg'],
    description: 'Premium noise-cancelling headphones with exceptional sound quality.',
    specs: {
      'Type': 'Over-ear Wireless',
      'Noise Cancellation': 'Active',
      'Battery': '30 hours',
      'Bluetooth': '5.0',
      'Audio Codec': 'LDAC',
      'Weight': '250g',
    },
    inStock: true,
    featured: true,
  },
  {
    id: '21',
    name: 'ASUS ZenBook Pro',
    category: 'laptop',
    brand: 'ASUS',
    price: 119999,
    rating: 4.7,
    reviews: 234,
    image: '/products/asus-zenbook-pro.jpg',
    images: ['/products/asus-zenbook-pro.jpg', '/products/asus-zenbook-pro-2.jpg'],
    description: 'Premium ultrabook with stunning display and powerful performance.',
    specs: {
      'Processor': 'Intel i9-13th Gen',
      'RAM': '32GB LPDDR5',
      'Storage': '1TB SSD',
      'Display': '15.6" 4K OLED',
      'Weight': '1.90 kg',
      'Battery': 'Up to 13 hours',
    },
    inStock: true,
    featured: true,
    discount: 8,
  },
  {
    id: '22',
    name: 'HP Spectre x360',
    category: 'laptop',
    brand: 'HP',
    price: 99999,
    rating: 4.6,
    reviews: 198,
    image: '/products/hp-spectre-x360.jpg',
    images: ['/products/hp-spectre-x360.jpg', '/products/hp-spectre-x360-2.jpg'],
    description: 'Convertible 2-in-1 laptop with touchscreen and stylus support.',
    specs: {
      'Processor': 'Intel i7-1360P',
      'RAM': '16GB LPDDR5',
      'Storage': '512GB SSD',
      'Display': '13.3" 2-in-1 Touch',
      'Weight': '1.36 kg',
      'Battery': 'Up to 11 hours',
    },
    inStock: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured).slice(0, 6);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.brand.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery)
  );
}

export function getCategories() {
  return ['laptop', 'desktop', 'tablet', 'accessories'];
}
